name: Copool
options:
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 6.0
    MACOSX_DEPLOYMENT_TARGET: "14.0"
targets:
  Copool:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources/Copool
    resources:
      - path: Sources/Copool/Resources
    settings:
      base:
        PRODUCT_NAME: icopool
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleName: icopool
        INFOPLIST_KEY_CFBundleDisplayName: icopool
        INFOPLIST_KEY_LSMinimumSystemVersion: "14.0"
        INFOPLIST_KEY_LSUIElement: YES
        CODE_SIGN_STYLE: Automatic
        CURRENT_PROJECT_VERSION: 28
        MARKETING_VERSION: 2.1.0
        DEVELOPMENT_TEAM: KLU8GF65GP
        PRODUCT_BUNDLE_IDENTIFIER: com.alick.copool
  CopoolTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Tests/CopoolTests
    dependencies:
      - target: Copool
schemes:
  Copool:
    build:
      targets:
        Copool: all
        CopoolTests: [test]
    test:
      targets:
        - CopoolTests
